export const SERVICES = [
  {
    id: 1,
    serviceName: 'Naturopathic Consultation',
    charge: '$50 / hour',
    rating: '4.8',
    clinicName: 'SUNBEAR SHIATSU',
    spaceName: 'HAWTHORN',
    srcImage: 'assets/img/card-img-1.png',
    availableDate: 'Today, June 28',
    appointmentSlots: ['11:00 AM', '11:15 AM'],
  },
  {
    id: 2,
    serviceName: 'Naturopathic Consultation',
    charge: '$50 / hour',
    rating: '4.8',
    clinicName: 'SUNBEAR SHIATSU',
    spaceName: 'HAWTHORN',
    srcImage: 'assets/img/card-img-2.png',
    availableDate: 'Today, June 28',
    appointmentSlots: ['11:00 AM', '11:15 AM'],
  },
  {
    id: 3,
    serviceName: 'Naturopathic Consultation',
    charge: '$50 / hour',
    rating: '4.8',
    clinicName: 'SUNBEAR SHIATSU',
    spaceName: 'HAWTHORN',
    srcImage: 'assets/img/card-img-3.png',
    availableDate: 'Today, June 28',
    appointmentSlots: ['11:00 AM', '11:15 AM'],
  },
  {
    id: 4,
    serviceName: 'Naturopathic Consultation',
    charge: '$50 / hour',
    rating: '4.8',
    clinicName: 'SUNBEAR SHIATSU',
    spaceName: 'HAWTHORN',
    srcImage: 'assets/img/card-img-4.png',
    availableDate: 'Today, June 28',
    appointmentSlots: ['11:00 AM', '11:15 AM'],
  },
];
